name: Add extracted translations snapshot to TMS
on:
  pull_request:
    types: [ closed ]
jobs:
  add-snapshot-to-tms:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: lokalise
        uses: ./
        with:
          actions-rc: ./test-workflows/.translate-actionrc.yml
          command: addSnapshot

          lokaliseApi: ${{ secrets.LOKALISE_API }}
          lokaliseProject: ${{ secrets.LOKALISE_PROJECT }}
          lokaliseSourceLanguageCode: source

          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
          owner: ScientaNL
          repo: lokalise-tms-github-action

          dynamoDBAccessKey: ${{ secrets.AWS_DYNAMODB_ACCESS_KEY_ID }}
          dynamoDBSecret: ${{ secrets.AWS_DYNAMODB_SECRET_ACCESS_KEY }}
          dynamoDBTable: translation-keys
          AWSRegion: eu-west-3
