name: Extract translations and store snapshot
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  extract-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: lokalise
        uses: ./
        with:
          actions-rc: ./test-workflows/.translate-actionrc.yml
          command: extract
          mockGithub: true

          lokaliseApi: ${{ secrets.LOKALISE_API }}
          lokaliseProject: ${{ secrets.LOKALISE_PROJECT }}

          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
          owner: ScientaNL
          repo: lokalise-tms-github-action

          mockStoragePath: ./test-workflows/tmp
